import re

_RE_NONALNUM = re.compile(r"[^a-z0-9]+")


def _norm(s):
    return _RE_NONALNUM.sub(" ", str(s).lower())


def _norm_multi(*parts):
    return " ".join(_norm(p) for p in parts)


CURATED = [
    ("Deep Learning (Goodfellow)", ["goodfellow", "deep", "learning"]),
    ("Deep Learning (Goodfellow) - ISBN alt", ["deep", "learning", "adaptive", "computation"]),
    ("Pattern Recognition and Machine Learning (Bishop)", ["bishop", "pattern", "recognition", "machine", "learning"]),
    ("PRML acronym", ["prml"]),
    ("Machine Learning: A Probabilistic Perspective (Murphy)", ["murphy", "machine", "learning", "probabilistic", "perspective"]),
    ("Probabilistic Machine Learning (Murphy)", ["murphy", "probabilistic", "machine", "learning"]),
    ("Probabilistic ML: An Introduction (Murphy)", ["murphy", "introduction", "probabilistic"]),
    ("Machine Learning: An Algorithmic Perspective (Marsland)", ["marsland", "machine", "learning", "algorithmic"]),
    ("Hands-On Machine Learning (Géron)", ["geron", "hands-on", "machine", "learning"]),
    ("Hands-On Machine Learning (Aurélien) title alt", ["hands-on", "machine", "learning", "scikit-learn", "keras", "tensorflow"]),
    ("Python Machine Learning (Raschka)", ["raschka", "python", "machine", "learning"]),
    ("Machine Learning with PyTorch and Scikit-Learn (Raschka)", ["raschka", "pytorch", "scikit-learn"]),
    ("Machine Learning Yearning (Ng)", ["ng", "machine", "learning", "yearning"]),
    ("The Elements of Statistical Learning (Hastie)", ["hastie", "elements", "statistical", "learning"]),
    ("Introduction to Statistical Learning (James)", ["james", "introduction", "statistical", "learning"]),
    ("ISLR acronym", ["islr"]),
    ("Artificial Intelligence: A Modern Approach (Russell & Norvig)", ["russell", "artificial", "intelligence", "modern", "approach"]),
    ("Artificial Intelligence: A Modern Approach (Norvig alt)", ["norvig", "artificial", "intelligence", "modern"]),
    ("Reinforcement Learning: An Introduction (Sutton & Barto)", ["sutton", "reinforcement", "learning", "introduction"]),
    ("Reinforcement Learning: An Introduction (Barto alt)", ["barto", "reinforcement", "learning"]),
    ("Deep Learning with Python (Chollet)", ["chollet", "deep", "learning", "python"]),
    ("Deep Learning with PyTorch (Stevens)", ["stevens", "deep", "learning", "pytorch"]),
    ("Dive into Deep Learning (Zhang)", ["zhang", "dive", "deep", "learning"]),
    ("Dive into Deep Learning acronym (d2l)", ["d2l"]),
    ("Neural Networks and Deep Learning (Nielsen)", ["nielsen", "neural", "networks", "deep", "learning"]),
    ("Deep Learning: A Practitioner's Approach", ["practitioner", "deep", "learning"]),
    ("Deep Learning (Kelleher)", ["kelleher", "deep", "learning"]),
    ("Deep Learning Fundamentals (Glassner)", ["glassner", "deep", "learning"]),
    ("Deep Learning Illustrated (Krohn)", ["krohn", "deep", "learning", "illustrated"]),
    ("Neural Networks: A Comprehensive Foundation (Haykin)", ["haykin", "neural", "networks", "comprehensive", "foundation"]),
    ("Neural Network Methods in NLP (Goldberg)", ["goldberg", "neural", "network", "methods", "natural", "language"]),
    ("Speech and Language Processing (Jurafsky & Martin)", ["jurafsky", "speech", "language", "processing"]),
    ("Speech and Language Processing (Martin alt)", ["martin", "speech", "language", "processing"]),
    ("Foundations of Statistical NLP (Manning)", ["manning", "foundations", "statistical", "natural", "language"]),
    ("Natural Language Processing with Python (Bird)", ["bird", "natural", "language", "processing", "python"]),
    ("Pattern Recognition and ML challenges", ["pattern", "classification", "duda"]),
    ("Pattern Classification (Duda)", ["duda", "pattern", "classification"]),
    ("Pattern Recognition and ML (Theodoridis)", ["theodoridis", "pattern", "recognition"]),
    ("Machine Learning (Mitchell)", ["mitchell", "machine", "learning"]),
    ("Pattern Recognition (Theodoridis early)", ["theodoridis", "pattern", "recognition", "machine"]),
    ("Computer Vision: Algorithms and Applications (Szeliski)", ["szeliski", "computer", "vision", "algorithms", "applications"]),
    ("Computer Vision: Models, Learning, and Inference (Prince)", ["prince", "computer", "vision", "models", "learning", "inference"]),
    ("Computer Vision: A Modern Approach (Forsyth)", ["forsyth", "computer", "vision", "modern", "approach"]),
    ("Probabilistic Graphical Models (Koller)", ["koller", "probabilistic", "graphical", "models"]),
    ("Graphical Models... (Jordan) - Intro to PGMs", ["jordan", "introduction", "probabilistic", "graphical"]),
    ("Information Theory, Inference and Learning Algorithms (MacKay)", ["mackay", "information", "theory", "inference", "learning", "algorithms"]),
    ("Bayesian Reasoning and Machine Learning (Barber)", ["barber", "bayesian", "reasoning", "machine", "learning"]),
    ("The Hundred-Page Machine Learning Book (Burkov)", ["burkov", "hundred-page", "machine", "learning"]),
    ("Approaching Almost Any ML Problem (Thakur)", ["thakur", "approaching", "machine", "learning"]),
    ("Designing Machine Learning Systems (Huyen)", ["huyen", "designing", "machine", "learning", "systems"]),
    ("Machine Learning Design Patterns", ["machine", "learning", "design", "patterns"]),
    ("Hands-On Unsupervised Learning (Patel)", ["patel", "hands-on", "unsupervised", "learning"]),
    ("Feature Engineering for ML (Zheng)", ["zheng", "feature", "engineering", "machine", "learning"]),
    ("An Introduction to Statistical Learning - Python (James)", ["james", "introduction", "statistical", "learning", "python"]),
    ("Mathematics for Machine Learning (Deisenroth)", ["deisenroth", "mathematics", "machine", "learning"]),
    ("Linear Algebra and Learning from Data (Strang)", ["strang", "linear", "algebra", "learning", "data"]),
    ("Introduction to Applied Linear Algebra (Boyd)", ["boyd", "introduction", "applied", "linear", "algebra"]),
    ("Convex Optimization (Boyd)", ["boyd", "convex", "optimization"]),
    ("Data Science from Scratch (Grus)", ["grus", "data", "science", "scratch"]),
    ("Python Data Science Handbook (VanderPlas)", ["vanderplas", "python", "data", "science", "handbook"]),
    ("Practical Statistics for Data Scientists (Bruce)", ["bruce", "practical", "statistics", "data", "scientists"]),
    ("Introduction to Machine Learning with Python (Müller)", ["muller", "introduction", "machine", "learning", "python"]),
    ("Machine Learning for Absolute Beginners", ["machine", "learning", "absolute", "beginners"]),
    ("AI: A Very Short Introduction (Boden)", ["boden", "artificial", "intelligence", "very", "short"]),
    ("Superintelligence (Bostrom)", ["bostrom", "superintelligence"]),
    ("Life 3.0 (Tegmark)", ["tegmark", "life", "3.0"]),
    ("Human Compatible (Russell)", ["russell", "human", "compatible"]),
    ("The Alignment Problem (Christian)", ["christian", "alignment", "problem"]),
    ("Weapons of Math Destruction (O'Neil)", ["o'neil", "weapons", "math", "destruction"]),
    ("The Master Algorithm (Domingos)", ["domingos", "master", "algorithm"]),
    ("Grokking Deep Learning (Trask)", ["trask", "grokking", "deep", "learning"]),
    ("Grokking Algorithms (Bhargava)", ["bhargava", "grokking", "algorithms"]),
    ("Grokking Machine Learning (Serrano)", ["serrano", "grokking", "machine", "learning"]),
    ("The Deep Learning Revolution (Sejnowski)", ["sejnowski", "deep", "learning", "revolution"]),
    ("Genius Makers (Metz)", ["metz", "genius", "makers"]),
    ("The Book of Why (Pearl)", ["pearl", "book", "why"]),
    ("Causal Inference in Statistics (Pearl)", ["pearl", "causal", "inference", "statistics"]),
    ("The Art of Statistics (Spiegelhalter)", ["spiegelhalter", "art", "statistics"]),
    ("Naked Statistics (Wheelan)", ["wheelan", "naked", "statistics"]),
    ("How to Lie with Statistics (Huff)", ["huff", "how", "lie", "statistics"]),
    ("Python for Data Analysis (McKinney)", ["mckinney", "python", "data", "analysis"]),
    ("High-Dimensional Statistics (Wainwright)", ["wainwright", "high-dimensional", "statistics"]),
    ("Foundations of Machine Learning (Mohri)", ["mohri", "foundations", "machine", "learning"]),
    ("Understanding Machine Learning (Shalev-Shwartz)", ["shalev", "understanding", "machine", "learning"]),
    ("Learning from Data (Abu-Mostafa)", ["abu-mostafa", "learning", "data"]),
    ("Interpretable Machine Learning (Molnar)", ["molnar", "interpretable", "machine", "learning"]),
    ("Machine Learning for Hackers (Conway)", ["conway", "machine", "learning", "hackers"]),
    ("Doing Data Science (O'Neil)", ["doing", "data", "science"]),
    ("The Myth of Artificial Intelligence (Larson)", ["larson", "myth", "artificial", "intelligence"]),
    ("Artificial Intelligence Basics (Taulli)", ["taulli", "artificial", "intelligence", "basics"]),
    ("Multiple View Geometry in Computer Vision (Hartley)", ['hartley', 'multiple', 'view']),
    ("Digital Image Processing (Gonzalez)", ['gonzalez', 'digital', 'image']),
    ("Learning OpenCV (Bradski)", ['bradski', 'learning', 'opencv']),
    ("Programming Computer Vision with Python (Solem)", ['solem', 'programming', 'computer']),
    ("Introductory Techniques for 3-D Computer Vision (Trucco)", ['trucco', 'introductory', 'techniques']),
    ("Numerical Optimization (Nocedal)", ['nocedal', 'numerical', 'optimization']),
    ("Introductory Lectures on Convex Optimization (Nesterov)", ['nesterov', 'introductory', 'lectures', 'convex', 'optimization']),
    ("Convex Analysis (Rockafellar)", ['rockafellar', 'convex', 'analysis']),
    ("Optimization for Machine Learning (Sra)", ['sra', 'optimization', 'machine', 'learning']),
    ("Algorithms for Optimization (Kochenderfer)", ['kochenderfer', 'algorithms', 'optimization']),
    ("Deep Generative Modeling (Jakub M. Tomczak)", ['tomczak', 'deep', 'generative']),
    ("Generative Deep Learning (David Foster)", ['foster', 'generative', 'deep']),
    ("An Introduction to Variational Autoencoders (Kingma and Welling)", ['kingma', 'variational', 'autoencoders']),
    ("Normalizing Flows for Probabilistic Modeling and Inference (George Papamakarios)", ['papamakarios', 'normalizing', 'flows']),
    ("Generative AI with Python and TensorFlow 2 (Babcock and Bali)", ['babcock', 'generative']),
    ("GANs in Action (Jakub Langr and Vladimir Bok)", ['langr', 'gans', 'action']),
    ("Graph Representation Learning (Hamilton)", ['hamilton', 'graph', 'representation', 'learning']),
    ("Deep Learning on Graphs (Ma)", ['deep', 'learning', 'graphs']),
    ("Geometric Deep Learning: Grids, Groups, Graphs, Geodesics, and Gauges (Bronstein)", ['bronstein', 'geometric', 'deep', 'learning']),
    ("Graph Neural Networks: Foundations, Frontiers, and Applications (Wu)", ['graph', 'neural', 'networks']),
    ("Introduction to Graph Neural Networks (Liu)", ['liu', 'introduction', 'graph', 'neural', 'networks']),
    ("Hands-On Graph Neural Networks Using Python (Labonne)", ['labonne', 'hands-on', 'graph', 'neural', 'networks']),
    ("Forecasting: Principles and Practice (Hyndman)", ['hyndman', 'forecasting', 'principles', 'practice']),
    ("Time Series Analysis: Forecasting and Control (Box)", ['time', 'series', 'forecasting']),
    ("Time Series Analysis and Its Applications: With R Examples (Shumway)", ['shumway', 'time', 'series', 'applications']),
    ("Introduction to Time Series and Forecasting (Brockwell)", ['brockwell', 'introduction', 'time', 'series']),
    ("Outlier Analysis (Aggarwal)", ['aggarwal', 'outlier', 'analysis']),
    ("Anomaly Detection: Principles and Algorithms (Mehrotra)", ['mehrotra', 'anomaly', 'detection', 'principles']),
    ("Causal Inference: The Mixtape (Scott Cunningham)", ['cunningham', 'causal', 'inference']),
    ("Mostly Harmless Econometrics: An Empiricist's Companion (Joshua D. Angrist and Jörn-Steffen Pischke)", ['angrist', 'mostly', 'harmless']),
    ("Causal Inference for Statistics, Social, and Biomedical Sciences: An Introduction (Guido W. Imbens and Donald B. Rubin)", ['imbens', 'causal', 'inference']),
    ("Counterfactuals and Causal Inference: Methods and Principles for Social Research (Stephen L. Morgan and Christopher Winship)", ['morgan', 'counterfactuals', 'causal']),
    ("Elements of Causal Inference: Foundations and Learning Algorithms (Jonas Peters, Dominik Janzing, and Bernhard Schölkopf)", ['peters', 'elements', 'causal']),
    ("Causal Inference: What If (Miguel A. Hernán and James M. Robins)", ['hernan', 'causal', 'inference']),
    ("Linear Algebra and Its Applications (Strang)", ['strang', 'linear', 'algebra', 'applications']),
    ("Matrix Analysis (Horn)", ['horn', 'matrix', 'analysis']),
    ("Calculus (Apostol)", ['apostol', 'calculus']),
    ("Introduction to Probability (Blitzstein)", ['blitzstein', 'introduction', 'probability']),
    ("Probability and Statistics (DeGroot)", ['degroot', 'probability', 'statistics']),
    ("Fundamentals of Numerical Computation (Trefethen)", ['trefethen', 'numerical', 'computation']),
    ("Markov Decision Processes (Puterman)", ['puterman', 'markov', 'decision', 'processes']),
    ("Bandit Algorithms (Lattimore)", ['lattimore', 'bandit', 'algorithms']),
    ("Algorithms for Reinforcement Learning (Szepesvari)", ['szepesvari', 'algorithms', 'reinforcement', 'learning']),
    ("Neuro-Dynamic Programming (Bertsekas)", ['bertsekas', 'neuro-dynamic', 'programming']),
    ("Reinforcement Learning and Optimal Control (Bertsekas)", ['bertsekas', 'reinforcement', 'optimal', 'control']),
    ("Decision Making Under Uncertainty (Kochenderfer)", ['kochenderfer', 'decision', 'making', 'uncertainty']),
    ("Bayesian Data Analysis (Gelman)", ['gelman', 'bayesian', 'data', 'analysis']),
    ("Statistical Rethinking (McElreath)", ['mcelreath', 'statistical', 'rethinking']),
    ("Bayesian Methods for Hackers (Davidson-Pilon)", ['davidson-pilon', 'bayesian', 'methods', 'hackers']),
    ("Bayesian Statistics the Fun Way (Kurt)", ['kurt', 'bayesian', 'statistics']),
    ("Model-Based Machine Learning (Winn)", ['winn', 'model-based', 'machine', 'learning']),
    ("The BUGS Book (Lunn)", ['lunn', 'bugs']),
    ("Statistical Models (Freedman)", ['freedman', 'statistical', 'models']),
    ("All of Statistics (Wasserman)", ['wasserman', 'statistics']),
    ("Computer Age Statistical Inference (Efron)", ['efron', 'computer', 'statistical', 'inference']),
    ("An Introduction to Categorical Data Analysis (Agresti)", ['agresti', 'introduction', 'categorical', 'data', 'analysis']),
    ("Time Series Analysis and Its Applications (Shumway)", ['shumway', 'time', 'series', 'analysis']),
    ("Design and Analysis of Experiments (Montgomery)", ['montgomery', 'design', 'analysis', 'experiments']),
    ("Fundamentals of Speech Recognition (Rabiner)", ['rabiner', 'fundamentals', 'speech', 'recognition']),
    ("Automatic Speech Recognition (Yu)", ['automatic', 'speech', 'recognition']),
    ("Deep Learning for NLP and Speech Recognition (Kamath)", ['kamath', 'deep', 'learning', 'speech', 'recognition']),
    ("The Scientist and Engineer's Guide to Digital Signal Processing (Smith)", ['smith', 'digital', 'signal', 'processing']),
    ("Digital Signal Processing (Proakis)", ['proakis', 'digital', 'signal', 'processing']),
    ("Planning Algorithms (LaValle)", ['lavalle', 'planning', 'algorithms']),
    ("Probabilistic Robotics (Thrun)", ['thrun', 'probabilistic', 'robotics']),
    ("Modern Robotics (Lynch)", ['lynch', 'modern', 'robotics']),
    ("Robotics, Vision and Control (Corke)", ['corke', 'robotics', 'vision', 'control']),
    ("Introduction to Autonomous Mobile Robots (Siegwart)", ['siegwart', 'autonomous', 'mobile', 'robots']),
    ("Underactuated Robotics (Tedrake)", ['tedrake', 'underactuated', 'robotics']),
    ("Natural Language Understanding (Allen)", ['allen', 'natural', 'language', 'understanding']),
    ("Introduction to Information Retrieval (Manning)", ['manning', 'introduction', 'information', 'retrieval']),
    ("Neural Machine Translation (Koehn)", ['koehn', 'neural', 'machine', 'translation']),
    ("Statistical Machine Translation (Koehn)", ['koehn', 'statistical', 'machine', 'translation']),
    ("Transformers for Natural Language Processing (Rothman)", ['rothman', 'transformers', 'natural', 'language', 'processing']),
    ("Elements of Information Theory (Cover)", ['cover', 'elements', 'information', 'theory']),
    ("The Information: A History, a Theory, a Flood (Gleick)", ['gleick', 'information', 'history', 'theory', 'flood']),
    ("A Mathematical Theory of Communication (Shannon)", ['shannon', 'mathematical', 'theory', 'communication']),
    ("Network Information Theory (El Gamal)", ['el gamal', 'network', 'information', 'theory']),

    # --- from daolf/Most-recommended-programming-books ---
    ("Continuous Delivery (Jez Humble & David Farley)", ['humble', 'continuous', 'delivery']),
    ("Algorithms (Robert Sedgewick & Kevin Wayne)", ['sedgewick', 'algorithms']),
    ("The Self-Taught Programmer (Cory Althoff)", ['althoff', 'self', 'taught', 'programmer']),
    ("Rapid Development (Steve McConnell)", ['mcconnell', 'rapid', 'development']),
    ("Coders at Work (Peter Seibel)", ['seibel', 'coders', 'work']),
    ("Domain-Driven Design (Eric Evans)", ['evans', 'domain', 'driven', 'design']),
    ("Structure and Interpretation of Computer Programs (Harold Abelson)", ['abelson', 'structure', 'interpretation', 'computer', 'programs']),
    ("Patterns of Enterprise Application Architecture (Martin Fowler)", ['fowler', 'patterns', 'enterprise', 'application', 'architecture']),
    ("Programming Pearls (Jon Bentley)", ['bentley', 'programming', 'pearls']),
    ("Peopleware (Tom DeMarco & Tim Lister)", ['demarco', 'peopleware']),
    ("Introduction to Algorithms (Thomas H. Cormen)", ['cormen', 'introduction', 'algorithms']),
    ("Code (Charles Petzold)", ['petzold', 'code']),
    ("Don't Make Me Think (Steve Krug)", ['krug', 'make', 'think']),
    ("Soft Skills (John Sonmez)", ['sonmez', 'soft', 'skills']),
    ("Cracking the Coding Interview (Gayle Laakmann McDowell)", ['mcdowell', 'cracking', 'coding', 'interview']),
    ("Design Patterns (Erich Gamma)", ['gamma', 'design', 'patterns']),
    ("Working Effectively with Legacy Code (Michael Feathers)", ['feathers', 'working', 'effectively', 'legacy', 'code']),
    ("The Clean Coder (Robert Martin)", ['martin', 'clean', 'coder']),
    ("The Mythical Man-Month (Frederick P. Brooks)", ['brooks', 'mythical', 'man', 'month']),
    ("Head First Design Patterns (Eric Freeman)", ['freeman', 'head', 'first', 'design', 'patterns']),
    ("Refactoring (Martin Fowler)", ['fowler', 'refactoring']),
    ("Code Complete (Steve McConnell)", ['mcconnell', 'code', 'complete']),
    ("Clean Code (Robert C. Martin)", ['martin', 'clean', 'code']),
    ("The Pragmatic Programmer (David Thomas)", ['thomas', 'pragmatic', 'programmer']),

]


def match_quality(title, handle):
    haystack = _norm_multi(title, handle)
    for _, keys in CURATED:
        if all(_norm(k) in haystack for k in keys):
            return True
    return False